version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
         name: Install Docker Compose
         command: |
           curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
           chmod +x ~/docker-compose
           sudo mv ~/docker-compose /usr/local/bin/docker-compose
     - run:
         name: "Running test service with docker compose"
         command: |
          set -ex
          docker-compose up -d test_db
          docker-compose up --exit-code-from tests_service tests_service
     - run:
         name: "Running test api with docker compose"
         command: |
           set -ex
           docker-compose up -d test_db
           docker-compose up --exit-code-from tests_api tests_api
     - run:
         name: "Running integration test with docker compose"
         command: |
           set -ex
           docker-compose up -d db
           docker-compose up -d caeli_service
           docker-compose up -d caeli_api
           sudo apt-get update -y
           sudo apt-get upgrade -y
           sudo install -y httpie jq
           sleep 5
           http GET localhost:5000/stats | jq -e '.[] | .repository'
